// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVl9ej3INJWJdPQDeEaHXc0tRjBTVdm3Y',
    appId: '1:312150853521:web:2a894f7a19bfa11e7bbc30',
    messagingSenderId: '312150853521',
    projectId: 'fluttermessageapp-7820f',
    authDomain: 'fluttermessageapp-7820f.firebaseapp.com',
    storageBucket: 'fluttermessageapp-7820f.appspot.com',
    measurementId: 'G-292J6ENKX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAi1FWMPW7DRHQd3_rZS_pnTR_m4NlJoA',
    appId: '1:312150853521:android:ce39b60e54d72ca17bbc30',
    messagingSenderId: '312150853521',
    projectId: 'fluttermessageapp-7820f',
    storageBucket: 'fluttermessageapp-7820f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtsEVEWyQ-XRjsSIf-vB63dGrmiQaz5E8',
    appId: '1:312150853521:ios:8dd120a43955e5927bbc30',
    messagingSenderId: '312150853521',
    projectId: 'fluttermessageapp-7820f',
    storageBucket: 'fluttermessageapp-7820f.appspot.com',
    androidClientId: '312150853521-7diqellsivv5en8h0ag3ult3icdjvncp.apps.googleusercontent.com',
    iosClientId: '312150853521-4tnj01925nf3gc3ettr3qrpi6i64v63f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtsEVEWyQ-XRjsSIf-vB63dGrmiQaz5E8',
    appId: '1:312150853521:ios:69657a6d7757004e7bbc30',
    messagingSenderId: '312150853521',
    projectId: 'fluttermessageapp-7820f',
    storageBucket: 'fluttermessageapp-7820f.appspot.com',
    androidClientId: '312150853521-7diqellsivv5en8h0ag3ult3icdjvncp.apps.googleusercontent.com',
    iosClientId: '312150853521-dho1a55d1fs0g55a2bfeuftqgq2machr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
